OnlineShop/Areas/Admin/Controllers/FooterController.cs
using Models_OnlineShop.DAO;
using Models_OnlineShop.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class FooterController : BaseController
    {
        // GET: Admin/Footer
        public ActionResult Index( int page = 1, int pageSize = 1)
        {
            var model = new FooterDao().ListAllPaging( page, pageSize);
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Footer footer)
        {
            if (ModelState.IsValid)
            {
                long id = new FooterDao().Insert(footer);
                if (id > 0)
                {
                    setAlert("Thêm thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    setAlert("Thêm thất bại", "error");
                }
            }
            return View();         
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var model = new FooterDao().ViewDetail(id);
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Footer footer)
        {
            if (ModelState.IsValid)
            {
             
                bool detail = new FooterDao().Update(footer);
                if (detail)
                {
                    setAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật không thành công");

                }


            }
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(long id)
        {
            new FooterDao().Delete(id);
            return RedirectToAction("Index");
        }

        public JsonResult changeStatus(long id)
        {
            var detail = new FooterDao().changeStatus(id);
            return Json(new
            {
                status = detail
            });
        }
    }
}

OnlineShop/Areas/Admin/Views/Footer/Create.cshtml
@model Models_OnlineShop.EF.Footer

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    Thêm Chân trang
}
@section jsFooter{
    <script>
 
        var editor = CKEDITOR.replace('txtContent', {
            customConfig: '/Assets/admin/js/plugins/ckeditor/config.js'
        })
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Thêm chân trang
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        @using (Html.BeginForm("Create","Footer",FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } ,id="txtContent"})
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.CheckBoxFor(model => model.Status)
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Tạo mới" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("<< Quay lại danh sách", "Index")
</div>

OnlineShop/Areas/Admin/Views/Footer/Edit.cshtml
@model Models_OnlineShop.EF.Footer

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    Cập nhật chân trang
}
@section jsFooter{
    <script>

        var editor = CKEDITOR.replace('txtContent', {
            customConfig: '/Assets/admin/js/plugins/ckeditor/config.js'
        })
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Thêm chân trang
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        @using (Html.BeginForm("Edit", "Footer", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" }, id = "txtContent" })
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.CheckBoxFor(model => model.Status)
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Cập nhật" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("<< Quay lại danh sách", "Index")
</div>

OnlineShop/Areas/Admin/Views/Footer/Index.cshtml
@model PagedList.IPagedList<Models_OnlineShop.EF.Footer>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Giới thiệu
}

@section jsFooter{
    <script src="~/Assets/admin/js/controller/statuscontroller.js?t=1491313943549"></script>

}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Quản lý giới thiệu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <div class="row form-group">
                    <div class="col-lg-12">

                        <div class="col-md-4">
                            <a class="btn btn-primary" href="/Admin/Footer/Create">Thêm</a>
                        </div>


                    </div>
                </div>


                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>

                                <th>Nội Dung</th>
                                <th>Trạng thái</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">

                                    <td>@Html.Raw(item.Content)</td>

                                    <td>
                                        <a href="#" class="btn-active-footer" data-id="@item.ID">@(item.Status?"Kích hoạt":"Khóa")</a>
                                    </td>
                                    <td>
                                        <a href="/Admin/Footer/Edit/@item.ID">Sửa</a> |
                                        @Ajax.ActionLink("Xóa", "Delete", new { @id = item.ID }, new AjaxOptions
                                   {
                                       Confirm = "Bạn muốn xóa bản ghi này?",
                                       OnComplete = "$('#row_" + @item.ID + "').remove()",
                                       //remove dòng chứa id này trong view
                                       HttpMethod = "Delete"

                                   })


                                    </td>
                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.searchString }))
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>