OnlineShop/Areas/Admin/Controllers/ProductController.cs
using Models_OnlineShop.DAO;
using Models_OnlineShop.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using OnlineShop.Common;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Admin/Product
        public ActionResult Index(string searchString, int page = 1, int pageSize = 5)
        {
            ViewBag.searchString = searchString;
            var product = new ProductDao().ListAllPaging(searchString, page, pageSize);
            return View(product);
        }
        [HttpGet]
        public ActionResult Create()
        {
            setViewBag();
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.USER_SESSION];
                product.CreatedDate = DateTime.Now;
                product.MetaTiltle = StringHelper.ToUnsignString(product.Name);
                product.CreatedBy = session.UserName;
                product.ShowOnHome = false;
                var dao = new ProductDao();
                long id = dao.insert(product);

                if (id > 0)
                {
                    setAlert("Thêm thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm không thành công");

                }

            }
            setViewBag();
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            new ProductDao().Delete(id);
            return RedirectToAction("Index");

        }

        [HttpPost]
        public JsonResult changeStatus(long id)
        {
            var dao = new ProductDao();
            var result = dao.changeStatus(id);
            return Json(new
            {
                status = result
            });
        }
        [HttpGet]
        public ActionResult Edit(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            setViewBag();
            return View(product);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.USER_SESSION];
                product.ModifyDate = DateTime.Now;
                product.MetaTiltle = StringHelper.ToUnsignString(product.Name);
                product.ModifyBy = session.UserName;
                product.ShowOnHome = false;
                var dao = new ProductDao();
               var detail = dao.update(product);

                if (detail )
                {
                    setAlert("Sửa thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Sửa không thành công");

                }

            }
            setViewBag();
            return View();
        }
        public void setViewBag(long? selectID = null)
        {
            var dao = new ProductCategoryDao();
            ViewBag.CategoryID = new SelectList(dao.ListAll(), "ID", "Name", selectID);
            var mainmenu = new MenuDao().ListByGroupID(1);
            ViewBag.MainMenuID = new SelectList(mainmenu, "ID", "Text", selectID);
            var tags = new TagDao().ListAll();
            ViewBag.TagID = new SelectList(tags, "ID", "Name", selectID);

        }
    }
}

OnlineShop/Controllers/ProductController.cs
using Models_OnlineShop.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(long id, int type = 1, int PageNumber = 1, int PageSize = 9)
        {
            if (type == 1)
            {
                var ListProduct = new ProductDao().ListByProductCategory(id, PageNumber, PageSize);
                return View(ListProduct);
            }
            else if(type == 2)
            {
                var ListProduct = new ProductDao().ListByMainMenu(id, PageNumber, PageSize);
                return View(ListProduct);
            }
            else
            {
                var ListProduct = new ProductDao().ListByTag(id, PageNumber, PageSize);
                return View(ListProduct);
            }
    
            
        }
        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            },JsonRequestBehavior.AllowGet); 
        }
        public ActionResult Search(string keyword, int page = 1, int pageSize = 9)
        {       
            int totalRecord = 0;
            var product = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);
            //tổng sán phẩm
            ViewBag.Total = totalRecord;
            //trang được chọn
            ViewBag.Page = page;

            ViewBag.Keyword = keyword;

            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(product);
        }
    
        [ChildActionOnly]
        public ActionResult Seller()
        {
            var ListProduct = new ProductDao().ListAllPaging("", 1, 3);
            return PartialView(ListProduct);
        }
        [ChildActionOnly]
        public ActionResult ProductCategory()
        {
            var productcategory = new ProductCategoryDao().ListAll();
            return PartialView(productcategory);
        }
      
        [ChildActionOnly]
        public ActionResult Tags()
        {

            return PartialView();
        }
       
        public ActionResult Detail(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.RelatedProduct = new ProductDao().ListRelatedProduct(id,3);
            return View(product);
        }
    }
}

OnlineShop/Controllers/TagController.cs
using Models_OnlineShop.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Tags()
        {
            var tags = new TagDao().ListAll();
            return PartialView(tags);
        }
    }
}

OnlineShop/Views/Product/Detail.cshtml
@model Models_OnlineShop.EF.Product
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var relatedProduct = (List<Models_OnlineShop.EF.Product>)ViewBag.RelatedProduct;
}
@section JsFooter{

    <script src="~/Assets/client/js/controller/cartcontroller.js"></script>
}
<div class="single">

    <div class="container">
        <div class="col-md-9">
            <div class="content-top">
                <h1>Thông tin chi tiết sản phẩm</h1>
            </div>
            <div class="col-md-5 grid">
                <div class="flexslider">
                    <div class="thumb-image"> <img src="@Model.Image" data-imagezoom="true" class="img-responsive"> </div>
                </div>
            </div>
            <div class="col-md-7 single-top-in">
                <div class="single-para simpleCart_shelfItem">
                    <h1>@Model.Name</h1>
                    <p>@Model.Description</p>
                    @*<div class="star-on">
                    <ul>
                        <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                    </ul>
                    <div class="review">
                        <a href="#"> 3 reviews </a>/
                        <a href="#">  Write a review</a>
                    </div>
                    <div class="clearfix"> </div>
                </div>*@

                    <label class="add-to item_price">@Model.Price</label>

                    <div class="available">
                        <h6>Available Options :</h6>
                        <ul>

                            <li>
                                Size:<select>
                                    <option>Large</option>
                                    <option>Medium</option>
                                    <option>small</option>
                                    <option>Large</option>
                                    <option>small</option>
                                </select>
                            </li>
                            <li>
                                Cost:
                                <select>
                                    <option>U.S.Dollar</option>
                                    <option>Euro</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                    <a href="#" id="additem" data-id="@Model.ID" data-qty="1" class="cart item_add">Add To Cart</a>
                </div>
            </div>
            <div class="clearfix"> </div>
            <div class="content-top1">
                @foreach (var item in relatedProduct)
                {
                    <div class="col-md-4 col-md3">
                        <div class="col-md1 simpleCart_shelfItem">
                            <a href="/chi-tiet/@item.MetaTiltle-@item.ID">
                                <img class="img-responsive" src="@item.Image" alt="" />
                            </a>
                            <h3><a href="single.html">@item.Name</a></h3>
                            <div class="price">
                                <h5 class="item_price">@item.Price</h5>
                                <a href="#" id="additem" data-id="@Model.ID" data-qty="1" class="cart item_add">Add To Cart</a>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                }               
                <div class="clearfix"> </div>
            </div>

        </div>
        <div class="col-md-3 product-bottom">
            @{ Html.RenderAction("ProductCategory", "Product");}

            <!--initiate accordion-->
            <script type="text/javascript">
                $(function () {
                    var menu_ul = $('.menu-drop > li > ul'),
                        menu_a = $('.menu-drop > li > a');
                    menu_ul.hide();
                    menu_a.click(function (e) {
                        e.preventDefault();
                        if (!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true, true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true, true).slideUp('normal');
                        }
                    });

                });
            </script>
            <!--//menu-->
            <!--seller-->
            @{ Html.RenderAction("Seller", "Product");}
            <!--//seller-->
            <!--tag-->
            @{ Html.RenderAction("Tags", "Tag");}

        </div>

        <div class="clearfix"> </div>
    </div>
</div>

OnlineShop/Views/Product/Index.cshtml
@model PagedList.IPagedList<Models_OnlineShop.EF.Product>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="single">
    <div class="container">
        <div class="col-md-12">
            <div class="col-md-9 grid">
                <div class="content-top">
                    <h1>Danh sách sản phẩm</h1>
                    <div class="content-top1">
                        @foreach (var item in Model)
                        {
                            var DetailsURL = "/chi-tiet/" + item.MetaTiltle + "-" + item.ID;
                            <div class="col-md-4 col-md3">
                                <div class="col-md1 simpleCart_shelfItem">
                                    <a href="@DetailsURL">
                                        <img class="img-responsive" src="@item.Image" alt="" />
                                    </a>
                                    <h3><a href="@DetailsURL">@item.Name</a></h3>
                                    <div class="price">
                                        <h5 class="item_price">@item.Price VND</h5>
                                        <a href="#" class="item_add">Add To Cart</a>
                                        <div class="clearfix"> </div>
                                    </div>
                                </div>
                            </div>
                        }

                        <div class="clearfix"> </div>
                    </div>
                    @Html.PagedListPager(Model, PageNumber => Url.Action("Index", new { PageNumber}))
                </div>
            </div>


        <div class="col-md-3 product-bottom">
            @{ Html.RenderAction("ProductCategory", "Product");}

            <!--initiate accordion-->
            <script type="text/javascript">
                $(function () {
                    var menu_ul = $('.menu-drop > li > ul'),
                        menu_a = $('.menu-drop > li > a');
                    menu_ul.hide();
                    menu_a.click(function (e) {
                        e.preventDefault();
                        if (!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true, true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true, true).slideUp('normal');
                        }
                    });

                });
            </script>
            <!--//menu-->
            <!--seller-->
            @{ Html.RenderAction("Seller", "Product");}          
            <!--//seller-->
            <!--tag-->
            @{ Html.RenderAction("Tags", "Tag");}
           
        </div>

        </div>
    </div>
</div>

OnlineShop/Views/Product/Search.cshtml
@model List<Models_OnlineShop.ViewModel.ProductViewModel>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="products">
    <div class="container">
        <h1>Kết quả tìm kiếm:@ViewBag.Keyword</h1>
        <div class="col-md-9">
            @*<div class="content-top1">*@
            @if (Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <div class="col-md-4 col-md3">
                        <div class="col-md1 simpleCart_shelfItem">
                            <a href="single.html">
                                <img class="img-responsive" src="@item.Images" alt="" />
                            </a>
                            <h3><a href="single.html">@item.Name</a></h3>
                            <div class="price">
                                <h5 class="item_price">@item.Price</h5>
                                <a href="#" id="additem" data-id="@item.ID" data-qty="1" class="item_add">Add To Cart</a>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                }
                <div class="clear"></div>
                if (ViewBag.TotalPage > 1)
                {
                    var pageDisplay = (int)ViewBag.MaxPage;
                    int totalPage = (int)ViewBag.TotalPage;
                    int currentPage = ((int)ViewBag.Page);

                    // Create numeric links
                    var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
                    var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

                    var link = "/tin-kiem?keyword=" + ViewBag.Keyword;
                    <nav>
                        <ul class="pagination clear">
                            @if (currentPage > ViewBag.First)
                            {
                                <li><a href="@link&page=@ViewBag.First" title="Trang đầu" class="first"><i class="fa fa-angle-double-left"></i></a></li>
                                <li>
                                    <a href="@link&page=@ViewBag.Prev" title="Trang trước" class="prev"><i class="fa fa-angle-left"></i></a>
                                </li>
                            }
                            @for (int i = startPageIndex; i <= endPageIndex; i++)
                            {
                                if (currentPage == i)
                                {

                                    <li> <a href="@link&page=@i" class="active" title="Trang @i">@i</a></li>
                                }
                                else
                                {
                                    <li><a href="@link&page=@i" title="Trang @i" class="pos">@i</a></li>
                                }
                            }
                            @if (currentPage < totalPage)
                            {
                                <li><a href="@link&page=@ViewBag.Next" class="next" title="Trang sau"><i class="fa fa-angle-right"></i></a></li>
                                <li> <a href="@link&page=@ViewBag.Last" class="last" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>
                            }

                        </ul>
                    </nav>
                }
            }
        </div>


        <div class="col-md-3 product-bottom">
            @{ Html.RenderAction("ProductCategory", "Product");}

            <!--initiate accordion-->
            <script type="text/javascript">
                $(function () {
                    var menu_ul = $('.menu-drop > li > ul'),
                        menu_a = $('.menu-drop > li > a');
                    menu_ul.hide();
                    menu_a.click(function (e) {
                        e.preventDefault();
                        if (!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true, true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true, true).slideUp('normal');
                        }
                    });

                });
            </script>
            <!--//menu-->
            <!--seller-->
            @{ Html.RenderAction("Seller", "Product");}
            <!--//seller-->
            <!--tag-->
            @{ Html.RenderAction("Tags", "Tag");}

        </div>

    </div>
</div>
</div>