OnlineShop/Areas/Admin/Controllers/FeedbackController.cs
using Models_OnlineShop.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class FeedbackController : BaseController
    {
        // GET: Admin/Feedback
        public ActionResult Index(string searchString ,int page=1,int pageSize=10)
        {
            ViewBag.searchString = searchString;
            var feedback = new FeedbackDao().ListAllPaging(searchString,page,pageSize);
            return View(feedback);
        }
    }
}

OnlineShop/Areas/Admin/Views/Feedback/Index.cshtml
@model PagedList.IPagedList<Models_OnlineShop.EF.Feedback>
@using PagedList.Mvc
@{
    ViewBag.Title = "Danh sách";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    Danh sách phản hồi
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Danh sách phản hồi
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Index", "Feedback", FormMethod.Get))
                {
                    <div class="row form-group">
                        <div class="col-lg-12">
                            <div class="col-md-4">
                                <input type="text" value="@ViewBag.searchString" class="form-control" name="searchString" />
                            </div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-success">Tìm kiếm</button>

                            </div>


                        </div>
                    </div>
                }

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>

                                <th>Tên</th>
                                <th>Điện thoại</th>
                                <th>Email</th>
                                <th>Địa chỉ</th>
                                <th>Nội Dung</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">

                                    <td>@item.Name</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Email</td>
                                    <td>@item.Address</td>
                                    <td>@item.Content</td>

                                    @*<td>
                                             <a href="/Admin/Product/Edit/@item.ID">Sửa</a> |
                                             @Ajax.ActionLink("Xóa", "Delete", new { @id = item.ID }, new AjaxOptions
                                        {
                                            Confirm = "Bạn muốn xóa bản ghi này?",
                                            OnComplete = "$('#row_" + @item.ID + "').remove()",
                                            //remove dòng chứa id này trong view
                                            HttpMethod = "Delete"

                                        })


                                         </td>*@
                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.searchString }))
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>